--------------------------------------------------------
-- Archivo creado  - lunes-abril-03-2017   
--------------------------------------------------------

--------------------------------------------------------
--  DDL for Sequence FUNCTIONARY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."FUNCTIONARY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence FUNCTION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."FUNCTION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PLACE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."PLACE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PRODUCT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."PRODUCT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ROLE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."ROLE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SALEITEM_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."SALEITEM_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SALE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."SALE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MEALSERVICE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."MEALSERVICE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."USERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence VOUCHERAMOUNT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."VOUCHERAMOUNT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence VOUCHER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."VOUCHER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence WORKSHIFT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."WORKSHIFT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence WSASSINGMENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PORTAFOLIO"."WSASSINGMENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table FUNCTION
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."FUNCTION" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(64 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FUNCTIONARY
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."FUNCTIONARY" 
   (	"ID" NUMBER(*,0), 
	"PASSWORD" VARCHAR2(128 BYTE), 
	"RUT" NUMBER(*,0), 
	"NAME" VARCHAR2(64 BYTE), 
	"SURNAME" VARCHAR2(64 BYTE), 
	"FUNCTION_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PLACE
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."PLACE" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(128 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."PRODUCT" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(64 BYTE), 
	"PRICE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROLE
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."ROLE" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(64 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SALE
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."SALE" 
   (	"ID" NUMBER(*,0), 
	"TOTAL" NUMBER(*,0), 
	"PLACE_ID" NUMBER(*,0), 
	"VOUCHER_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SALEITEM
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."SALEITEM" 
   (	"ID" NUMBER(*,0), 
	"QUANTITY" VARCHAR2(20 BYTE), 
	"SALE_ID" NUMBER(*,0), 
	"PRODUCT_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEALSERVICE
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."MEALSERVICE" 
   (	"ID" NUMBER(*,0), 
	"STARTTIME" DATE, 
	"ENDTIME" DATE, 
	"PRODUCT_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."USERS" 
   (	"ID" NUMBER(*,0), 
	"PASSWORD" VARCHAR2(128 BYTE), 
	"ROLE_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VOUCHER
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."VOUCHER" 
   (	"ID" NUMBER(*,0), 
	"CODE" VARCHAR2(6 BYTE), 
	"USED" CHAR(1 BYTE), 
	"DATETIME" DATE, 
	"VOUCHERAMOUNT_ID" NUMBER(*,0), 
	"FUNCTIONARY_ID" NUMBER(*,0), 
	"SALE_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VOUCHERAMOUNT
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."VOUCHERAMOUNT" 
   (	"ID" NUMBER(*,0), 
	"AMOUNT" NUMBER(*,0), 
	"SERVICE_ID" NUMBER(*,0), 
	"FUNCTION_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table WORKSHIFT
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."WORKSHIFT" 
   (	"ID" NUMBER(*,0), 
	"STARTTIME" DATE, 
	"ENDTIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table WSASSINGMENT
--------------------------------------------------------

  CREATE TABLE "PORTAFOLIO"."WSASSINGMENT" 
   (	"ID" NUMBER(*,0), 
	"STARTDATE" DATE, 
	"ENDDATE" DATE, 
	"WORKSHIFT_ID" NUMBER(*,0), 
	"FUNCTIONARY_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."USERS_PK" ON "PORTAFOLIO"."USERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index WORKSHIFT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."WORKSHIFT_PK" ON "PORTAFOLIO"."WORKSHIFT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SALE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."SALE_PK" ON "PORTAFOLIO"."SALE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SERVICE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."SERVICE_PK" ON "PORTAFOLIO"."MEALSERVICE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FUNCTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."FUNCTION_PK" ON "PORTAFOLIO"."FUNCTION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ROLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."ROLE_PK" ON "PORTAFOLIO"."ROLE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PLACE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."PLACE_PK" ON "PORTAFOLIO"."PLACE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SALEITEM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."SALEITEM_PK" ON "PORTAFOLIO"."SALEITEM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FUNCTIONARY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."FUNCTIONARY_PK" ON "PORTAFOLIO"."FUNCTIONARY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VOUCHERAMOUNT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."VOUCHERAMOUNT_PK" ON "PORTAFOLIO"."VOUCHERAMOUNT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRODUCT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."PRODUCT_PK" ON "PORTAFOLIO"."PRODUCT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index WSASSINGMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."WSASSINGMENT_PK" ON "PORTAFOLIO"."WSASSINGMENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VOUCHER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PORTAFOLIO"."VOUCHER_PK" ON "PORTAFOLIO"."VOUCHER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."PRODUCT" ADD CONSTRAINT "PRODUCT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."PRODUCT" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."PRODUCT" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."PRODUCT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SALE
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."SALE" ADD CONSTRAINT "SALE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."SALE" MODIFY ("VOUCHER_ID" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."SALE" MODIFY ("PLACE_ID" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."SALE" MODIFY ("TOTAL" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."SALE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PLACE
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."PLACE" ADD CONSTRAINT "PLACE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."PLACE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."PLACE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FUNCTION
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."FUNCTION" ADD CONSTRAINT "FUNCTION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."FUNCTION" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."FUNCTION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FUNCTIONARY
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."FUNCTIONARY" ADD CONSTRAINT "FUNCTIONARY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."FUNCTIONARY" MODIFY ("FUNCTION_ID" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."FUNCTIONARY" MODIFY ("SURNAME" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."FUNCTIONARY" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."FUNCTIONARY" MODIFY ("RUT" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."FUNCTIONARY" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."FUNCTIONARY" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VOUCHERAMOUNT
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."VOUCHERAMOUNT" ADD CONSTRAINT "VOUCHERAMOUNT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."VOUCHERAMOUNT" MODIFY ("FUNCTION_ID" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."VOUCHERAMOUNT" MODIFY ("SERVICE_ID" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."VOUCHERAMOUNT" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."VOUCHERAMOUNT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."USERS" MODIFY ("ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."USERS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table WSASSINGMENT
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."WSASSINGMENT" ADD CONSTRAINT "WSASSINGMENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."WSASSINGMENT" MODIFY ("FUNCTIONARY_ID" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."WSASSINGMENT" MODIFY ("WORKSHIFT_ID" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."WSASSINGMENT" MODIFY ("ENDDATE" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."WSASSINGMENT" MODIFY ("STARTDATE" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."WSASSINGMENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SALEITEM
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."SALEITEM" ADD CONSTRAINT "SALEITEM_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."SALEITEM" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."SALEITEM" MODIFY ("SALE_ID" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."SALEITEM" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."SALEITEM" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VOUCHER
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."VOUCHER" ADD CHECK ("USED" IN(0,1)) ENABLE;
  ALTER TABLE "PORTAFOLIO"."VOUCHER" MODIFY ("SALE_ID" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."VOUCHER" MODIFY ("FUNCTIONARY_ID" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."VOUCHER" MODIFY ("VOUCHERAMOUNT_ID" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."VOUCHER" ADD CONSTRAINT "VOUCHER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."VOUCHER" MODIFY ("DATETIME" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."VOUCHER" MODIFY ("USED" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."VOUCHER" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."VOUCHER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEALSERVICE
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."MEALSERVICE" ADD CONSTRAINT "SERVICE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."MEALSERVICE" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."MEALSERVICE" MODIFY ("ENDTIME" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."MEALSERVICE" MODIFY ("STARTTIME" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."MEALSERVICE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROLE
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."ROLE" ADD CONSTRAINT "ROLE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."ROLE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."ROLE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table WORKSHIFT
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."WORKSHIFT" ADD CONSTRAINT "WORKSHIFT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PORTAFOLIO"."WORKSHIFT" MODIFY ("ENDTIME" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."WORKSHIFT" MODIFY ("STARTTIME" NOT NULL ENABLE);
  ALTER TABLE "PORTAFOLIO"."WORKSHIFT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table FUNCTIONARY
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."FUNCTIONARY" ADD CONSTRAINT "FUNCTIONARY_FK1" FOREIGN KEY ("FUNCTION_ID")
	  REFERENCES "PORTAFOLIO"."FUNCTION" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SALE
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."SALE" ADD CONSTRAINT "SALE_FK1" FOREIGN KEY ("PLACE_ID")
	  REFERENCES "PORTAFOLIO"."PLACE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PORTAFOLIO"."SALE" ADD CONSTRAINT "SALE_FK2" FOREIGN KEY ("VOUCHER_ID")
	  REFERENCES "PORTAFOLIO"."VOUCHER" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SALEITEM
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."SALEITEM" ADD CONSTRAINT "SALEITEM_FK1" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "PORTAFOLIO"."PRODUCT" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PORTAFOLIO"."SALEITEM" ADD CONSTRAINT "SALEITEM_FK2" FOREIGN KEY ("SALE_ID")
	  REFERENCES "PORTAFOLIO"."SALE" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MEALSERVICE
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."MEALSERVICE" ADD CONSTRAINT "SERVICE_FK1" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "PORTAFOLIO"."PRODUCT" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."USERS" ADD CONSTRAINT "USERS_FK1" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "PORTAFOLIO"."ROLE" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VOUCHER
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."VOUCHER" ADD CONSTRAINT "VOUCHER_FK1" FOREIGN KEY ("VOUCHERAMOUNT_ID")
	  REFERENCES "PORTAFOLIO"."VOUCHERAMOUNT" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PORTAFOLIO"."VOUCHER" ADD CONSTRAINT "VOUCHER_FK2" FOREIGN KEY ("FUNCTIONARY_ID")
	  REFERENCES "PORTAFOLIO"."FUNCTIONARY" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PORTAFOLIO"."VOUCHER" ADD CONSTRAINT "VOUCHER_FK3" FOREIGN KEY ("SALE_ID")
	  REFERENCES "PORTAFOLIO"."SALE" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VOUCHERAMOUNT
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."VOUCHERAMOUNT" ADD CONSTRAINT "VOUCHERAMOUNT_FK1" FOREIGN KEY ("FUNCTION_ID")
	  REFERENCES "PORTAFOLIO"."FUNCTION" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PORTAFOLIO"."VOUCHERAMOUNT" ADD CONSTRAINT "VOUCHERAMOUNT_FK2" FOREIGN KEY ("SERVICE_ID")
	  REFERENCES "PORTAFOLIO"."MEALSERVICE" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WSASSINGMENT
--------------------------------------------------------

  ALTER TABLE "PORTAFOLIO"."WSASSINGMENT" ADD CONSTRAINT "WSASSINGMENT_FK1" FOREIGN KEY ("WORKSHIFT_ID")
	  REFERENCES "PORTAFOLIO"."WORKSHIFT" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PORTAFOLIO"."WSASSINGMENT" ADD CONSTRAINT "WSASSINGMENT_FK2" FOREIGN KEY ("FUNCTIONARY_ID")
	  REFERENCES "PORTAFOLIO"."FUNCTIONARY" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  DDL for Trigger FUNCTIONARY_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."FUNCTIONARY_TRG" 
BEFORE INSERT ON FUNCTIONARY 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT FUNCTIONARY_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PORTAFOLIO"."FUNCTIONARY_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger FUNCTION_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."FUNCTION_TRG" 
BEFORE INSERT ON FUNCTION 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT FUNCTION_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PORTAFOLIO"."FUNCTION_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PLACE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."PLACE_TRG" 
BEFORE INSERT ON PLACE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT PLACE_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PORTAFOLIO"."PLACE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PRODUCT_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."PRODUCT_TRG" 
BEFORE INSERT ON PRODUCT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT PRODUCT_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PORTAFOLIO"."PRODUCT_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ROLE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."ROLE_TRG" 
BEFORE INSERT ON ROLE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT ROLE_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PORTAFOLIO"."ROLE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SALEITEM_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."SALEITEM_TRG" 
BEFORE INSERT ON SALEITEM 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT SALEITEM_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PORTAFOLIO"."SALEITEM_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SALE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."SALE_TRG" 
BEFORE INSERT ON SALE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT SALE_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PORTAFOLIO"."SALE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SERVICE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."SERVICE_TRG" 
BEFORE INSERT ON MEALSERVICE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT MEALSERVICE_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PORTAFOLIO"."SERVICE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USERS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."USERS_TRG" 
BEFORE INSERT ON USERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT USERS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PORTAFOLIO"."USERS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger VOUCHERAMOUNT_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."VOUCHERAMOUNT_TRG" 
BEFORE INSERT ON VOUCHERAMOUNT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT VOUCHERAMOUNT_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PORTAFOLIO"."VOUCHERAMOUNT_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger VOUCHER_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."VOUCHER_TRG" 
BEFORE INSERT ON VOUCHER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT VOUCHER_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PORTAFOLIO"."VOUCHER_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger WORKSHIFT_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."WORKSHIFT_TRG" 
BEFORE INSERT ON WORKSHIFT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT WORKSHIFT_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PORTAFOLIO"."WORKSHIFT_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger WSASSINGMENT_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PORTAFOLIO"."WSASSINGMENT_TRG" 
BEFORE INSERT ON WSASSINGMENT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT WSASSINGMENT_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PORTAFOLIO"."WSASSINGMENT_TRG" ENABLE;